title: Hassan Shahir
email: contact@hassanshahir.com
description: >-
  I'm Hassan. I like tech, philosophy, sleep, and working on my ideas. I'm 18. I go to school. I code. I read. I build & break and I think... (a lot).
baseurl: ""
url: "https://hassanshahir.com"

# Disable default theme (my own layout + style.css)
theme: null

# Plugins
plugins:
  - jekyll-feed

# Optional: exclude clutter
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
