base_url = "https://hassanshahir.com"
title = "Hassan Shahir"
description = "Essays, ideas, and projects."
default_language = "en"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
